ROUTINE Exercicio3
Exercicio3
 Read "Digite o primeiro numero: ", num1,!
 Read "Digite o segundo numero: ", num2,!
 Read "Digite o terceiro numero: ", num3,!
 set result1 = 0
 set result2 = 0
 set result3 = 0
 for x= num1:1:num2{
  if x#11=5{
   set result1 = result1 + 1
   write x_ "é divisivel por 11 com resto = 5",! 	  
  }
  set result3 = result3 + x	 
 }
 for x= num2:1:num3{
  if x#3=0{
   set result2 = result2 + 1
   write x_ "é divisivel por 3",! 	  
  }
 }
 
 w "Total de numero div 11 entre num1 e num2: "_result1,!
 w "Total de numero div 3 entre num2 e num3: "_result2,!
 w "Somatoria dos numeros entre num1 e num2: "_result3,!
 
 